#!/bin/sh
# Push mesh button to restart total network
# by kenvix

logger -t MeshButton "Mesh Button Action ${ACTION}."

if [ "${ACTION}" == "released" ]; then
    echo "Mesh Button Action Released. Ignored."
    exit 0
fi 

logger -t MeshButton "Mesh Button Action Pressed. Going to restart WAN."

echo "Going to set WAN down -- ubus: wan"
ubus call network.interface.wan down
echo "WAN is Down. Waiting ubus WAN interface"
ubus wait_for network.interface.wan
echo "WAN is ready. Going to set WAN up"
ubus call network.interface.wan up

logger -t MeshButton "WAN Restarted."